# .travis.yml
language:
  - python
python:
  - 2.7
notifications:
  - email: false
  - webhooks:
    - urls:
      - https://webhooks.gitter.im/e/cf61c08db5738d74d47c
    - on_success: always  # options: [always|never|change] default: always
    - on_failure: always  # options: [always|never|change] default: always
    - on_start: false     # default: false
install:
  - "pip install ."
  - "pip install -r requirements.txt"
script:
  - nosetests --with-coverage --cover-package=pyensemblrest --cover-erase --cover-html 
after_success:
  - coveralls
